### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by yozeng** [rivasiker/ilsmc#3]
Hi @rivasiker ,
When I was running model optimization of TRAILS, there was an issue with "No space left on device" in the /tmp directory. After troubleshooting, I found that there is still disk space left in /tmp, but the inode is exhausted. I guess this is due to the large number of temporary files generated by TRAILS. Do you have any suggestions?

**Comment by rivasiker** [comment]
Hi @yozeng!
The files in the tmp directory generated by TRAILS shouldn't take too much space (they are only a couple of big but manageable lookup tables). I have a couple of questions for you:
1. What version of TRAILS are you using? I'm guessing that you have the development version (v1.0.0).
2. What is your choice for `n_int_AB` and `n_int_ABC`? The larger the number of discretized intervals, the heavier the temporary files will be. 
3. Could you attach the full stderr output to the conversation?

**Comment by yozeng** [comment]
Thank you for your reply! Let me answer your questions first:

1. I installed TRAILS via conda and pip as instructed in the REDAME. When I run the `conda list` command, the version number shown is 0.0.1. Attached here is all the package information in my trails environment. [trails.txt](https://github.com/user-attachments/files/16499198/trails.txt)
2. I ran model optimization directly with the sample parameters from the README, and the only change is that I added the `t_out` parameter to the `dct` to be optimized. Thus, the values of `n_int_AB` and `n_int_ABC` are 3. Attached here is my model optimization script where the input maf file `../chrom.maf` is the alignment file of specific species quartet containing only one chromosome, which was generated by autocoalhmm. [model_opt.py.txt](https://github.com/user-attachments/files/16499234/model_opt.py.txt)
3. The command I executed was `nohup python model_opt.py > model_opt.log 2>&1 &`. The log file is attached here. [model_opt.log](https://github.com/user-attachments/files/16499254/model_opt.log)

I'd like to add some other information. After the program terminated, `df -h` shows that the root directory (/) has 36G of space left, while `df -i` shows that the inode of / is exhausted (6553600, 100%). When I moved the ray folder in the /tmp directory to another disk partition, `df -i` shows that the inode of / is only 3% used.

**Comment by rivasiker** [comment]
Thanks for the info! I think the problem is that you run out of RAM. The best for you would be to use the development version of TRAILS—I recently added some functionality that avoids using that much RAM, and instead writes the strictly necessary files on disk (in pkl format). In this version of TRAILS, you can specify the location of the temporary files in the `optimizer` function with the `tmp_path` argument, which defaults to `"./"` (the working directory). You can look up the source code [here](https://github.com/rivasiker/trails/blob/cddeedd5d55725d53742b04dce516b7b9550fe7e/src/trails/optimizer.py#L512C99-L512C114) (although it is still poorly documented). 

To install the development version, please run the following:
```
git clone https://github.com/rivasiker/trails.git
cd trails
pip3 install -e .
```
Let me know if you have trouble installing it. I've been meaning to make a new official release for TRAILS v1.0.0, but it will have to wait some months still. 

I think this will solve your problem, but if it persists, please let me know!

**Comment by yozeng** [comment]
Thank you for your suggestions! I will try to do that. I want to know if I should delete the current trails environment and then run following:
```
conda create -n trails -c conda-forge python=3.8 "ray-default" pandas numba numpy scipy biopython
conda activate trails
git clone https://github.com/rivasiker/trails.git
cd trails
pip3 install -e .
```
To be on the safe side, could you please tell me why you judge the problem to be RAM related? I thought inode was the main problem, but you don't seem to have mentioned it.
Actually, I did run a model optimization (without `t_out` in the `dct`) before this, but it was terminated by the OOM killer shortly after running (`n_eval` = 361, `time` = 40925.06160378456). I assumed it was just a random event. Also, while this run of model optimization took up a very large VIRT, the RES was relatively small (no more than 100G, and my cluster memory is 1T). (`n_eval` = 2182, `time` = 262716.1573088169)

**Comment by rivasiker** [comment]
I think you can directly try on your current environment, it's up to you!

About the possible cause of the problem, I really don't know. I just mentioned the RAM issue because it's what I had in the past. I never came across any inode problems myself. 

One more question—how many cores are you using to run your scripts?

**Comment by yozeng** [comment]
Thanks for your answer! I think setting the storage location of the temporary files to the working directory should solve the inode problem, since the working directory has a much larger number of inodes than /tmp.

As for the number of cores, I didn't specify it myself. By the way, is this something that can be specified? My cluster has 2 sockets with 64 cores each and 2 threads per core (Hyper-Threading).

**Comment by rivasiker** [comment]
I have only run TRAILS on compute nodes through slurm, where one must specify the amount of memory and the number of cores used. I'm guessing that you are already multithreading in your case.

Anyways, did you manage to solve your issue?

**Comment by yozeng** [comment]
I resubmitted the model optimization task after installing the development version. Since the `tmp_path` of the development version is the working directory by default, I didn't modify the contents of model_opt.py at first. But after submitting the task I found that the /tmp directory still had the **ray folder** I have mentioned before. So I specified `tmp_path = '. /'` in model_opt.py when `optimizer` is called, yet the ray folder still appeared in /tmp. It seems like my problem isn’t being solved, so I'm guessing that the temporary files specified by the `tmp_path` may not include the ray folder?

It should be noted that I didn't let the model optimization task run on because I have other tasks to do, so I'm not sure if the development version will allow this task to end properly.

Also, I'd like to ask a couple basic questions:

1. Is the maf file being passed to the `maf_parser` function an alignment file of specific species quartet containing only one chromosome? In other words, am I right to use the alignment file that was generated by autocoalhmm?
2. Did you submit the job via `sbatch` directly or via `gwf`? How much memory and how many cores should I request from slurm?
3. If I want to reconstruct the ancestral Ne and split times for a node, is it right to average the optimization results for all chromosomes of the node?

**Comment by rivasiker** [comment]
I have never had to change the ray tmp path, but I think you can do so by running `ray.init(_temp_dir="<your_custom_dir>")` as explained [here](https://github.com/ray-project/ray/issues/31478). 

Answering your other questions:
1. Technically, you could include as many chromosomes as you wish, though practically it might be unfeasible since the running time for computing the likelihood will increase with genome size. I myself have always run TRAILS (and previously CoalHMM) on single chromosomes. And yes, you can reuse the code for MafFilter in autoCoalHMM, but perhaps adapted to your own needs. 
2. I submitted to slurm via gwf. You can find the specifications I used [here](https://github.com/rivasiker/trails_paper/blob/main/chr1/scripts/workflow.py), which is the accompanying code for the original TRAILS publication (Rivas-González et al. 2024).
3. I have always averaged the resulting estimates weighted by the size of each chromosome. It is also potentially interesting to run TRAILS separately for each chromosome because it can give you an idea about the variability of your estimates, or about whether specific chromosomes have different effective population sizes.

**Comment by yozeng** [comment]
Thanks for your suggestions! But where should `ray.init(_temp_dir="<your_custom_dir>")` be added?

Additionally, I don't quite understand what "averaged the resulting estimates weighted by the size of each chromosome" means. Can you explain it for me? Thank you!

**Comment by rivasiker** [comment]
I think you can just add it before running `optimizer` (remember to import `ray` into the script, too). 

Imagine you have two chromosomes, chr1 having 200Mb and chr2 having 150Mb. If your estimate a certain parameter to be 0.4 for chr1 and 0.8 for chr2, you could take the mean (`(0.4+0.8)/2=0.6`), or a weighted average based on the length of the chromosomes, so `(0.4*200+0.8*150)/(200+150)=0.5714286`. The weighted average gives more weight to chr1, which is bigger. It's really up to you how you average the results, though!
